#!/usr/bin/env python3
"""Regenerates App/Features/Insights/WorldDots.swift, the land lattice behind
the Countries share card's dot-matrix world map.

Source: Natural Earth 1:110m "land" (ne_110m_land), public domain
(https://www.naturalearthdata.com/about/terms-of-use/). Only the land outline is
used. The card marks country centroids, so it never implies where inside a
country a connection ended up.

Lattice: equirectangular, 1 pt per degree, 360 pt wide, latitude 76° down to
-55° (131 pt), hexagonal rows 2.2 pt apart with odd rows shifted half a pitch.
A point is kept when it falls on land. Rows are written as run-length
"start,length" pairs, a few KB of string literal, because a 3,000-element array
literal takes the compiler seconds to type-check.

Usage:
    python3 Scripts/gen-world-dots.py path/to/ne_110m_land.geojson

Output is deterministic for a given input. Do not hand-edit the Swift file.
"""
import json
import os
import sys

from PIL import Image, ImageDraw

WIDTH, HEIGHT = 360, 131          # pt; 1 pt = 1 degree
LAT_TOP, LAT_BOTTOM = 76.0, -55.0
PITCH = 2.2                       # pt between dots
SCALE = 10                        # raster px per degree for the land test

if len(sys.argv) != 2:
    sys.exit(__doc__)
src = sys.argv[1]
here = os.path.dirname(os.path.abspath(__file__))
dst = os.path.join(here, "..", "App", "Features", "Insights", "WorldDots.swift")

with open(src) as f:
    geo = json.load(f)


def px(lon, lat):
    return ((lon + 180.0) * SCALE, (LAT_TOP - lat) * SCALE)


# Paint land white and every hole (Caspian, the big lakes) black, ring by
# ring in file order. In GeoJSON the first ring is the exterior and the
# rest are holes.
img = Image.new("L", (WIDTH * SCALE, HEIGHT * SCALE), 0)
draw = ImageDraw.Draw(img)
polys = []
for feature in geo["features"]:
    g = feature["geometry"]
    if g["type"] == "Polygon":
        polys.append(g["coordinates"])
    elif g["type"] == "MultiPolygon":
        polys.extend(g["coordinates"])
for rings in polys:
    for i, ring in enumerate(rings):
        pts = [px(lon, lat) for lon, lat in ring]
        draw.polygon(pts, fill=255 if i == 0 else 0)

pixels = img.load()
rows = []
y, row = PITCH / 2, 0
total = 0
while y < HEIGHT:
    x = PITCH / 2 + (PITCH / 2 if row % 2 else 0)
    col, runs, start = 0, [], None
    while x < WIDTH:
        land = pixels[min(int(x * SCALE), img.width - 1), min(int(y * SCALE), img.height - 1)] > 127
        if land and start is None:
            start = col
        if not land and start is not None:
            runs.append((start, col - start))
            start = None
        x += PITCH
        col += 1
    if start is not None:
        runs.append((start, col - start))
    total += sum(n for _, n in runs)
    rows.append(runs)
    y += PITCH
    row += 1

encoded = ";".join(" ".join(f"{s},{n}" for s, n in r) for r in rows)
build = geo.get("name", "ne_110m_land")

swift = f'''// Generated by Scripts/gen-world-dots.py. Do not edit by hand.
//
// Land lattice for the Countries share card's dot-matrix world: {total} points
// sampled from Natural Earth 1:110m land ({build}), which is public domain
// (naturalearthdata.com/about/terms-of-use). Equirectangular, 1 pt per degree,
// {WIDTH} × {HEIGHT} pt covering latitude {LAT_TOP:g}° to {LAT_BOTTOM:g}°, hexagonal rows
// {PITCH} pt apart. Stored as run-length rows so the compiler sees one string,
// not thousands of literals.

import CoreGraphics

enum WorldDots {{
    static let width: CGFloat = {WIDTH}
    static let height: CGFloat = {HEIGHT}
    static let latitudeTop: Double = {LAT_TOP:g}
    static let pitch: CGFloat = {PITCH}

    /// (x, y) of every land dot, in points, top-left origin. Decoded once.
    static let points: [CGPoint] = decode(runs)

    private static func decode(_ runs: String) -> [CGPoint] {{
        var out: [CGPoint] = []
        out.reserveCapacity({total})
        for (row, line) in runs.split(separator: ";", omittingEmptySubsequences: false).enumerated() {{
            let y = pitch / 2 + CGFloat(row) * pitch
            let shift: CGFloat = row % 2 == 1 ? pitch / 2 : 0
            for pair in line.split(separator: " ") {{
                let parts = pair.split(separator: ",")
                guard parts.count == 2, let start = Int(parts[0]), let count = Int(parts[1]) else {{ continue }}
                for col in start ..< start + count {{
                    out.append(CGPoint(x: pitch / 2 + shift + CGFloat(col) * pitch, y: y))
                }}
            }}
        }}
        return out
    }}

    private static let runs = "{encoded}"
}}
'''
with open(dst, "w") as f:
    f.write(swift)
print(f"{total} land dots, {len(encoded)} bytes of runs -> {os.path.relpath(dst)}")
