// Generated by Scripts/gen-world-dots.py. Do not edit by hand.
//
// Land lattice for the Countries share card's dot-matrix world: 3103 points
// sampled from Natural Earth 1:110m land (ne_110m_land), which is public domain
// (naturalearthdata.com/about/terms-of-use). Equirectangular, 1 pt per degree,
// 360 x 131 pt covering latitude 76° to -55°, hexagonal rows 2.2 pt apart.
// Stored as run-length rows so the compiler sees one string literal instead of
// thousands.

import CoreGraphics

enum WorldDots {
    static let width: CGFloat = 360
    static let height: CGFloat = 131
    static let latitudeTop: Double = 76
    static let pitch: CGFloat = 2.2

    /// (x, y) of every land dot, in points, top-left origin. Decoded once.
    static let points: [CGPoint] = decode(runs)

    private static func decode(_ runs: String) -> [CGPoint] {
        var out: [CGPoint] = []
        out.reserveCapacity(3103)
        for (row, line) in runs.split(separator: ";", omittingEmptySubsequences: false).enumerated() {
            let y = pitch / 2 + CGFloat(row) * pitch
            let shift: CGFloat = row % 2 == 1 ? pitch / 2 : 0
            for pair in line.split(separator: " ") {
                let parts = pair.split(separator: ",")
                guard parts.count == 2, let start = Int(parts[0]), let count = Int(parts[1]) else { continue }
                for col in start ..< start + count {
                    out.append(CGPoint(x: pitch / 2 + shift + CGFloat(col) * pitch, y: y))
                }
            }
        }
        return out
    }

    private static let runs = "30,2 38,1 40,5 56,17 107,2 121,12 145,2 149,1;24,3 28,5 35,2 38,1 40,5 56,15 105,2 113,1 115,1 118,22 145,2;9,5 30,5 38,2 41,10 57,13 92,4 112,3 116,39;0,1 6,23 32,2 36,5 42,2 48,3 57,11 88,11 101,1 105,7 113,50;1,4 6,37 48,3 52,1 57,8 71,1 73,2 88,10 99,1 101,63;8,32 42,1 44,1 48,4 58,5 71,3 86,5 92,70;6,33 46,3 59,3 84,6 92,69;8,3 12,1 18,20 46,4 51,1 84,6 93,56 150,2 154,2;10,1 21,20 47,7 79,2 86,3 93,52 153,3;7,1 22,22 46,9 79,2 85,1 91,52 152,3;23,22 46,10 78,1 80,2 84,63 153,1;24,30 55,1 79,66 146,1;25,25 51,2 55,3 80,67;25,29 81,14 96,1 99,5 106,38 146,1;25,26 52,1 81,7 89,6 99,4 105,39 146,1;25,25 77,6 85,1 87,2 90,4 96,1 100,3 105,35 145,1;25,23 78,4 91,1 94,10 106,30 137,1 139,1 145,1;26,21 77,4 87,1 91,1 94,10 106,29 136,1 139,1 144,1;27,20 79,1 81,6 93,1 98,38 139,2 142,4;28,17 77,10 97,39 140,2;29,16 77,13 91,46;29,9 44,1 76,27 104,33;30,1 32,6 44,1 75,22 98,7 108,28;32,5 74,23 98,7 106,1 112,23 136,1;34,3 43,1 45,2 74,25 100,9 113,10 124,9;10,1 33,4 40,2 74,24 100,8 114,6 124,6 131,1;36,6 74,25 101,6 115,5 125,5;39,4 74,25 101,4 115,3 126,5 136,1;41,3 74,29 116,2 128,4;42,1 47,3 74,27 103,2 116,2 126,1 128,3 138,1;44,10 76,29 118,1 126,1;46,9 76,28 127,1 134,1;47,11 78,1 84,1 86,18 125,1 128,1 134,2;46,12 86,16 126,1 128,1 132,3;45,14 86,15 127,2 131,4;45,16 86,14 127,2 131,3 135,2 141,1 143,2;45,20 87,13 129,1 136,2 143,5;45,20 87,12 129,2 144,5 152,1;46,20 88,12 135,2 146,1 148,1;46,19 88,12;47,17 88,12 104,1 141,3 146,1;47,17 87,13 103,1 138,5 146,1;49,15 87,12 102,2 137,8 146,2 162,1;49,14 87,10 102,2 136,13;50,13 88,10 101,3 134,16 157,1;49,11 88,9 101,2 133,17;50,10 89,8 133,18;49,10 89,7 133,18;49,10 90,6 134,17;49,8 90,4 134,4 142,8;49,7 145,5 160,1;48,7 145,5;48,6 161,1;48,4 147,2 159,2;49,3 159,1;47,4 157,2;47,5;47,3;48,3;49,3"
}
